// =============================================================================
// AUTO-GENERATED — DO NOT EDIT
// Generated by: config/scripts/generate-ts.js
// Network: base-sepolia (chainId: 84532)
// Generated at: 2026-02-03T10:53:39.021Z
// =============================================================================
// ---------------------------------------------------------------------------
// Network Configuration
// ---------------------------------------------------------------------------
export const NETWORK = 'base-sepolia';
export const CHAIN_ID = 84532;
export const RPC_URL = 'https://sepolia.base.org';
export const BLOCK_EXPLORER_URL = 'https://sepolia.basescan.org';
export const START_BLOCK = 36873479;
// ---------------------------------------------------------------------------
// Contract Addresses
// ---------------------------------------------------------------------------
export const CONTRACTS = {
    usdc: '0xd6897C4801c639Ff4eAaA31D7A5b4802613DB681',
    erc8004Registry: '0x454909C7551158e12a6a5192dEB359dDF067ec80',
    collateralVault: '0xC948389425061c2C960c034c1c9526E9E6f39ff9',
    termsRegistry: '0xBDc5328D4442A1e893CD2b1F75d3F64a3e50f923',
    councilRegistry: '0xAaA608c80168D90d77Ec5a7f72Fb939E7Add5C32',
    trustfulValidator: '0x9628C1bD875C3378B14f0108b60B0b5739fE92E8',
    claimsManager: '0x7B0465DF41c3649f88A627cF06941469BE9C7a44',
    rulingExecutor: '0x2a49b1826810AefAfFf93eC9317A426BbF8DC11f',
};
// Convenience aliases (backward compatibility)
export const USDC_ADDRESS = CONTRACTS.usdc;
export const ERC8004_REGISTRY_ADDRESS = CONTRACTS.erc8004Registry;
export const COLLATERAL_VAULT_ADDRESS = CONTRACTS.collateralVault;
export const TERMS_REGISTRY_ADDRESS = CONTRACTS.termsRegistry;
export const COUNCIL_REGISTRY_ADDRESS = CONTRACTS.councilRegistry;
export const TRUSTFUL_VALIDATOR_ADDRESS = CONTRACTS.trustfulValidator;
export const CLAIMS_MANAGER_ADDRESS = CONTRACTS.claimsManager;
export const RULING_EXECUTOR_ADDRESS = CONTRACTS.rulingExecutor;
// ---------------------------------------------------------------------------
// Safe Configuration
// ---------------------------------------------------------------------------
export const SAFE_ADDRESS = '0x568A391C188e2aF11FA7550ACca170e085B00e7F';
export const SAFE_TX_SERVICE_URL = 'https://safe-transaction-base-sepolia.safe.global';
export const SAFE_APP_URL = 'https://app.safe.global';
export const SAFE_NETWORK_PREFIX = 'basesep';
// ---------------------------------------------------------------------------
// Service URLs
// ---------------------------------------------------------------------------
export const API_URL = 'https://api.trustful-agents.ai';
export const SUBGRAPH_URL = 'https://api.studio.thegraph.com/query/1723244/trustful-agents/v1.3.1';
export const SUBGRAPH_VERSION = 'v1.3.1';
export const IPFS_GATEWAY = 'https://gateway.pinata.cloud/ipfs';
// ---------------------------------------------------------------------------
// Dashboard URLs
// ---------------------------------------------------------------------------
export const DASHBOARD_URLS = {
    provider: 'https://provider.trustful-agents.ai',
    claimer: 'https://claims.trustful-agents.ai',
    council: 'https://council.trustful-agents.ai',
    governance: 'https://governance.trustful-agents.ai',
};
// ---------------------------------------------------------------------------
// Database Configuration
// ---------------------------------------------------------------------------
export const DATABASE_NAME = 'trustful_governance_sepolia';
export const DATABASE_PORT = 5432;
// ---------------------------------------------------------------------------
// USDC Constants
// ---------------------------------------------------------------------------
export const USDC_DECIMALS = 6;
export const USDC_SYMBOL = 'USDC';
// ---------------------------------------------------------------------------
// Contract ABIs
// ---------------------------------------------------------------------------
export const ClaimsManagerAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimFiled",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimant",
                "type": "address",
                "indexed": true
            },
            {
                "name": "claimedAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "claimantDeposit",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "EvidenceSubmitted",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "evidenceHash",
                "type": "bytes32",
                "indexed": false
            },
            {
                "name": "evidenceUri",
                "type": "string",
                "indexed": false
            },
            {
                "name": "isCounterEvidence",
                "type": "bool",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "VoteCast",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "voter",
                "type": "address",
                "indexed": true
            },
            {
                "name": "vote",
                "type": "uint8",
                "indexed": false
            },
            {
                "name": "approvedAmount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "VoteChanged",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "voter",
                "type": "address",
                "indexed": true
            },
            {
                "name": "oldVote",
                "type": "uint8",
                "indexed": false
            },
            {
                "name": "newVote",
                "type": "uint8",
                "indexed": false
            },
            {
                "name": "oldApprovedAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "newApprovedAmount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimApproved",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "approvedAmount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimRejected",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimCancelled",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "depositForfeited",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimExpired",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "hadVotes",
                "type": "bool",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimExecuted",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "amountPaid",
                "type": "uint256",
                "indexed": false
            }
        ]
    }
];
export const CollateralVaultAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "Deposited",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "depositor",
                "type": "address",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "WithdrawalInitiated",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "executeAfter",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "WithdrawalCancelled",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "WithdrawalExecuted",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "recipient",
                "type": "address",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CollateralLocked",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CollateralUnlocked",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CollateralSlashed",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "recipient",
                "type": "address",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    }
];
export const CouncilRegistryAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "CouncilCreated",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "name",
                "type": "string",
                "indexed": false
            },
            {
                "name": "vertical",
                "type": "string",
                "indexed": false
            },
            {
                "name": "quorumPercentage",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "claimDepositPercentage",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CouncilClosed",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "timestamp",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CouncilUpdated",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CouncilDeactivated",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CouncilActivated",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "MemberAdded",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "member",
                "type": "address",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "MemberRemoved",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "member",
                "type": "address",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "MemberSuspended",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "member",
                "type": "address",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "MemberReinstated",
        "inputs": [
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "member",
                "type": "address",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "AgentCouncilReassigned",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "oldCouncilId",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "newCouncilId",
                "type": "bytes32",
                "indexed": true
            }
        ]
    }
];
export const ERC8004RegistryAbi = [
    {
        "type": "function",
        "name": "mint",
        "inputs": [
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "tokenId",
                "type": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "mintAuto",
        "inputs": [
            {
                "name": "to",
                "type": "address"
            }
        ],
        "outputs": [
            {
                "name": "tokenId",
                "type": "uint256"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "ownerOf",
        "inputs": [
            {
                "name": "tokenId",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [
            {
                "name": "owner",
                "type": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "nextTokenId",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "totalSupply",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "tokenOfOwnerByIndex",
        "inputs": [
            {
                "name": "owner",
                "type": "address"
            },
            {
                "name": "index",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "tokenURI",
        "inputs": [
            {
                "name": "tokenId",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "event",
        "name": "Transfer",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "indexed": true
            },
            {
                "name": "to",
                "type": "address",
                "indexed": true
            },
            {
                "name": "tokenId",
                "type": "uint256",
                "indexed": true
            }
        ]
    }
];
export const RulingExecutorAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "ClaimExecuted",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimant",
                "type": "address",
                "indexed": true
            },
            {
                "name": "compensationAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "councilFee",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "DepositDistributed",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "voterCount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "totalAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "amountPerVoter",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "DepositReturned",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "claimant",
                "type": "address",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "reason",
                "type": "string",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "CollateralUnlocked",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "amount",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "PartialExecution",
        "inputs": [
            {
                "name": "claimId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "requestedAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "actualAmount",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "reason",
                "type": "string",
                "indexed": false
            }
        ]
    }
];
export const TermsRegistryAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "TermsRegistered",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "version",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "contentHash",
                "type": "bytes32",
                "indexed": false
            },
            {
                "name": "contentUri",
                "type": "string",
                "indexed": false
            },
            {
                "name": "councilId",
                "type": "bytes32",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "TermsActivated",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "version",
                "type": "uint256",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "TermsDeactivated",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "version",
                "type": "uint256",
                "indexed": true
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "TermsInvalidated",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "reason",
                "type": "string",
                "indexed": false
            }
        ]
    }
];
export const TrustfulValidatorAbi = [
    {
        "type": "event",
        "anonymous": false,
        "name": "ValidationIssued",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "requestHash",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "nonce",
                "type": "uint256",
                "indexed": false
            },
            {
                "name": "responseUri",
                "type": "string",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ValidationRevoked",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "requestHash",
                "type": "bytes32",
                "indexed": true
            },
            {
                "name": "reason",
                "type": "uint8",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "anonymous": false,
        "name": "ValidationConditionsChanged",
        "inputs": [
            {
                "name": "agentId",
                "type": "uint256",
                "indexed": true
            },
            {
                "name": "conditions",
                "type": "tuple",
                "indexed": false,
                "components": [
                    {
                        "name": "hasMinimumCollateral",
                        "type": "bool"
                    },
                    {
                        "name": "hasActiveTerms",
                        "type": "bool"
                    },
                    {
                        "name": "isOwnerValid",
                        "type": "bool"
                    },
                    {
                        "name": "councilIsActive",
                        "type": "bool"
                    }
                ]
            }
        ]
    }
];
export const USDCAbi = [
    {
        "type": "function",
        "name": "mint",
        "inputs": [
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "amount",
                "type": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "approve",
        "inputs": [
            {
                "name": "spender",
                "type": "address"
            },
            {
                "name": "amount",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [
            {
                "name": "account",
                "type": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "allowance",
        "inputs": [
            {
                "name": "owner",
                "type": "address"
            },
            {
                "name": "spender",
                "type": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "decimals",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint8"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "totalSupply",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "transfer",
        "inputs": [
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "amount",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "transferFrom",
        "inputs": [
            {
                "name": "from",
                "type": "address"
            },
            {
                "name": "to",
                "type": "address"
            },
            {
                "name": "amount",
                "type": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "event",
        "name": "Transfer",
        "inputs": [
            {
                "name": "from",
                "type": "address",
                "indexed": true
            },
            {
                "name": "to",
                "type": "address",
                "indexed": true
            },
            {
                "name": "value",
                "type": "uint256",
                "indexed": false
            }
        ]
    },
    {
        "type": "event",
        "name": "Approval",
        "inputs": [
            {
                "name": "owner",
                "type": "address",
                "indexed": true
            },
            {
                "name": "spender",
                "type": "address",
                "indexed": true
            },
            {
                "name": "value",
                "type": "uint256",
                "indexed": false
            }
        ]
    }
];
// ---------------------------------------------------------------------------
// Legacy ABI Aliases (backward compatibility)
// ---------------------------------------------------------------------------
export const MockUsdcAbi = USDCAbi;
export const Erc8004RegistryAbi = ERC8004RegistryAbi;
//# sourceMappingURL=contracts.js.map