#!/usr/bin/env node

/**
 * generate-ts.js — Generates config/generated/contracts.ts
 * 
 * Reads the network JSON and all ABI files to produce a single TypeScript
 * module that both Vite frontends and the Node.js API can import.
 * 
 * Usage: node config/scripts/generate-ts.js [network]
 *        Default network: base-sepolia
 */

const fs = require('fs');
const path = require('path');

const network = process.argv[2] || 'base-sepolia';
const configDir = path.resolve(__dirname, '..');
const networkFile = path.join(configDir, 'networks', `${network}.json`);
const abisDir = path.join(configDir, 'abis');
const outputFile = path.join(configDir, 'generated', 'contracts.ts');

// ---------------------------------------------------------------------------
// Load network config
// ---------------------------------------------------------------------------

if (!fs.existsSync(networkFile)) {
  console.error(`Network config not found: ${networkFile}`);
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(networkFile, 'utf-8'));
console.log(`Generating contracts.ts for network: ${config.network} (chainId: ${config.chainId})`);

// ---------------------------------------------------------------------------
// Load ABIs
// ---------------------------------------------------------------------------

const abiFiles = fs.readdirSync(abisDir).filter(f => f.endsWith('.json'));
const abis = {};

for (const file of abiFiles) {
  const name = path.basename(file, '.json');
  const abi = JSON.parse(fs.readFileSync(path.join(abisDir, file), 'utf-8'));
  abis[name] = abi;
  console.log(`  Loaded ABI: ${name} (${abi.length} entries)`);
}

// ---------------------------------------------------------------------------
// Generate TypeScript
// ---------------------------------------------------------------------------

let ts = `// =============================================================================
// AUTO-GENERATED — DO NOT EDIT
// Generated by: config/scripts/generate-ts.js
// Network: ${config.network} (chainId: ${config.chainId})
// Generated at: ${new Date().toISOString()}
// =============================================================================

// ---------------------------------------------------------------------------
// Network Configuration
// ---------------------------------------------------------------------------

export const NETWORK = '${config.network}' as const;
export const CHAIN_ID: number = ${config.chainId};
export const RPC_URL = '${config.rpcUrl}';
export const BLOCK_EXPLORER_URL = '${config.blockExplorerUrl}';
export const START_BLOCK = ${config.startBlock};

// ---------------------------------------------------------------------------
// Contract Addresses
// ---------------------------------------------------------------------------

export const CONTRACTS = {
`;

for (const [name, address] of Object.entries(config.contracts)) {
  ts += `  ${name}: '${address}' as const,\n`;
}

ts += `} as const;

// Convenience aliases (backward compatibility)
`;

for (const [name, address] of Object.entries(config.contracts)) {
  const upperName = name.replace(/([A-Z])/g, '_$1').toUpperCase().replace(/^_/, '');
  ts += `export const ${upperName}_ADDRESS = CONTRACTS.${name};\n`;
}

ts += `
// ---------------------------------------------------------------------------
// Safe Configuration
// ---------------------------------------------------------------------------

export const SAFE_ADDRESS = '${config.safe.address}' as const;
export const SAFE_TX_SERVICE_URL = '${config.safe.txServiceUrl}';
export const SAFE_APP_URL = '${config.safe.appUrl}';
export const SAFE_NETWORK_PREFIX = '${config.safe.networkPrefix}';

// ---------------------------------------------------------------------------
// Service URLs
// ---------------------------------------------------------------------------

export const API_URL = '${config.services.apiUrl}';
export const SUBGRAPH_URL = '${config.services.subgraphUrl}';
export const SUBGRAPH_VERSION = '${config.services.subgraphVersion}';
export const IPFS_GATEWAY = '${config.services.ipfsGateway}';

// ---------------------------------------------------------------------------
// Dashboard URLs
// ---------------------------------------------------------------------------

export const DASHBOARD_URLS = {
`;

for (const [name, url] of Object.entries(config.dashboardUrls)) {
  ts += `  ${name}: '${url}',\n`;
}

ts += `} as const;

// ---------------------------------------------------------------------------
// Database Configuration
// ---------------------------------------------------------------------------

export const DATABASE_NAME = '${config.database.name}';
export const DATABASE_PORT = ${config.database.port};

// ---------------------------------------------------------------------------
// USDC Constants
// ---------------------------------------------------------------------------

export const USDC_DECIMALS = 6;
export const USDC_SYMBOL = 'USDC';

`;

// ---------------------------------------------------------------------------
// Generate ABI exports
// ---------------------------------------------------------------------------

ts += `// ---------------------------------------------------------------------------
// Contract ABIs
// ---------------------------------------------------------------------------

`;

for (const [name, abi] of Object.entries(abis)) {
  // Create the export name: ClaimsManager -> ClaimsManagerAbi
  const exportName = `${name}Abi`;
  ts += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

// Also export legacy names for backward compatibility
ts += `// ---------------------------------------------------------------------------
// Legacy ABI Aliases (backward compatibility)
// ---------------------------------------------------------------------------

export const MockUsdcAbi = USDCAbi;
export const Erc8004RegistryAbi = ERC8004RegistryAbi;
`;

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

const outputDir = path.dirname(outputFile);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputFile, ts);
console.log(`\nGenerated: ${outputFile} (${ts.length} bytes)`);
