#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# generate-env.sh — Generates .env files from network config JSON
#
# Usage: ./config/scripts/generate-env.sh [network]
#        Default network: base-sepolia
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(dirname "$SCRIPT_DIR")"
NETWORK="${1:-base-sepolia}"
NETWORK_FILE="$CONFIG_DIR/networks/${NETWORK}.json"
GENERATED_DIR="$CONFIG_DIR/generated"

if [ ! -f "$NETWORK_FILE" ]; then
  echo "ERROR: Network config not found: $NETWORK_FILE"
  exit 1
fi

mkdir -p "$GENERATED_DIR"

# Check for jq
if ! command -v jq &> /dev/null; then
  echo "ERROR: jq is required. Install with: sudo apt install jq"
  exit 1
fi

echo "Generating .env files for network: $NETWORK"

# =============================================================================
# Read values from JSON
# =============================================================================

CHAIN_ID=$(jq -r '.chainId' "$NETWORK_FILE")
RPC_URL=$(jq -r '.rpcUrl' "$NETWORK_FILE")
BLOCK_EXPLORER=$(jq -r '.blockExplorerUrl' "$NETWORK_FILE")

USDC=$(jq -r '.contracts.usdc' "$NETWORK_FILE")
ERC8004_REGISTRY=$(jq -r '.contracts.erc8004Registry // empty' "$NETWORK_FILE")
IDENTITY_REGISTRY=$(jq -r '.contracts.identityRegistry // empty' "$NETWORK_FILE")
VALIDATION_REGISTRY=$(jq -r '.contracts.validationRegistry // empty' "$NETWORK_FILE")
REPUTATION_REGISTRY=$(jq -r '.contracts.reputationRegistry // empty' "$NETWORK_FILE")
COLLATERAL_VAULT=$(jq -r '.contracts.collateralVault' "$NETWORK_FILE")
TERMS_REGISTRY=$(jq -r '.contracts.termsRegistry' "$NETWORK_FILE")
COUNCIL_REGISTRY=$(jq -r '.contracts.councilRegistry' "$NETWORK_FILE")
TRUSTFUL_VALIDATOR=$(jq -r '.contracts.trustfulValidator' "$NETWORK_FILE")
CLAIMS_MANAGER=$(jq -r '.contracts.claimsManager' "$NETWORK_FILE")
RULING_EXECUTOR=$(jq -r '.contracts.rulingExecutor' "$NETWORK_FILE")

SAFE_ADDRESS=$(jq -r '.safe.address' "$NETWORK_FILE")
SAFE_TX_SERVICE_URL=$(jq -r '.safe.txServiceUrl' "$NETWORK_FILE")

API_URL=$(jq -r '.services.apiUrl' "$NETWORK_FILE")
SUBGRAPH_URL=$(jq -r '.services.subgraphUrl' "$NETWORK_FILE")
SUBGRAPH_VERSION=$(jq -r '.services.subgraphVersion' "$NETWORK_FILE")
IPFS_GATEWAY=$(jq -r '.services.ipfsGateway' "$NETWORK_FILE")

DB_NAME=$(jq -r '.database.name' "$NETWORK_FILE")
DB_PORT=$(jq -r '.database.port' "$NETWORK_FILE")

PROVIDER_URL=$(jq -r '.dashboardUrls.provider' "$NETWORK_FILE")
CLAIMER_URL=$(jq -r '.dashboardUrls.claimer' "$NETWORK_FILE")
COUNCIL_URL=$(jq -r '.dashboardUrls.council' "$NETWORK_FILE")
GOVERNANCE_URL=$(jq -r '.dashboardUrls.governance' "$NETWORK_FILE")

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# =============================================================================
# Generate env.dashboard (VITE_ prefixed for Vite frontends)
# =============================================================================

cat > "$GENERATED_DIR/env.dashboard" <<EOF
# =============================================================================
# AUTO-GENERATED — DO NOT EDIT
# Generated by: config/scripts/generate-env.sh
# Network: $NETWORK (chainId: $CHAIN_ID)
# Generated at: $TIMESTAMP
# =============================================================================

# Network
VITE_NETWORK=$NETWORK
VITE_CHAIN_ID=$CHAIN_ID
VITE_RPC_URL=$RPC_URL
VITE_BLOCK_EXPLORER_URL=$BLOCK_EXPLORER

# Contract Addresses
VITE_USDC_ADDRESS=$USDC
VITE_ERC8004_REGISTRY_ADDRESS=$ERC8004_REGISTRY
VITE_IDENTITY_REGISTRY_ADDRESS=$IDENTITY_REGISTRY
VITE_VALIDATION_REGISTRY_ADDRESS=$VALIDATION_REGISTRY
VITE_REPUTATION_REGISTRY_ADDRESS=$REPUTATION_REGISTRY
VITE_COLLATERAL_VAULT_ADDRESS=$COLLATERAL_VAULT
VITE_TERMS_REGISTRY_ADDRESS=$TERMS_REGISTRY
VITE_COUNCIL_REGISTRY_ADDRESS=$COUNCIL_REGISTRY
VITE_TRUSTFUL_VALIDATOR_ADDRESS=$TRUSTFUL_VALIDATOR
VITE_CLAIMS_MANAGER_ADDRESS=$CLAIMS_MANAGER
VITE_RULING_EXECUTOR_ADDRESS=$RULING_EXECUTOR

# Safe
VITE_SAFE_ADDRESS=$SAFE_ADDRESS

# Services
VITE_API_URL=$API_URL
VITE_SUBGRAPH_URL=$SUBGRAPH_URL
VITE_IPFS_GATEWAY=$IPFS_GATEWAY
EOF

echo "  Generated: $GENERATED_DIR/env.dashboard"

# =============================================================================
# Generate env.api (server-side for governance-api)
# =============================================================================

cat > "$GENERATED_DIR/env.api" <<EOF
# =============================================================================
# AUTO-GENERATED — DO NOT EDIT
# Generated by: config/scripts/generate-env.sh
# Network: $NETWORK (chainId: $CHAIN_ID)
# Generated at: $TIMESTAMP
#
# Secrets (DB password, AWS, Pinata) go in .env.local — never in this file.
# =============================================================================

# Network
NETWORK=$NETWORK
CHAIN_ID=$CHAIN_ID
RPC_URL=$RPC_URL

# Contract Addresses
USDC_ADDRESS=$USDC
ERC8004_REGISTRY_ADDRESS=$ERC8004_REGISTRY
IDENTITY_REGISTRY_ADDRESS=$IDENTITY_REGISTRY
VALIDATION_REGISTRY_ADDRESS=$VALIDATION_REGISTRY
REPUTATION_REGISTRY_ADDRESS=$REPUTATION_REGISTRY
COLLATERAL_VAULT_ADDRESS=$COLLATERAL_VAULT
TERMS_REGISTRY_ADDRESS=$TERMS_REGISTRY
COUNCIL_REGISTRY_ADDRESS=$COUNCIL_REGISTRY
TRUSTFUL_VALIDATOR_ADDRESS=$TRUSTFUL_VALIDATOR
CLAIMS_MANAGER_ADDRESS=$CLAIMS_MANAGER
RULING_EXECUTOR_ADDRESS=$RULING_EXECUTOR

# Safe
SAFE_ADDRESS=$SAFE_ADDRESS
SAFE_TX_SERVICE_URL=$SAFE_TX_SERVICE_URL

# Services
API_URL=$API_URL
SUBGRAPH_URL=$SUBGRAPH_URL
SUBGRAPH_VERSION=$SUBGRAPH_VERSION
IPFS_GATEWAY=$IPFS_GATEWAY

# Database (credentials in .env.local)
DATABASE_NAME=$DB_NAME
DATABASE_PORT=$DB_PORT

# Dashboard URLs (for CORS, emails, metadata links)
PROVIDER_DASHBOARD_URL=$PROVIDER_URL
CLAIMER_DASHBOARD_URL=$CLAIMER_URL
COUNCIL_DASHBOARD_URL=$COUNCIL_URL
GOVERNANCE_DASHBOARD_URL=$GOVERNANCE_URL

# CORS (all dashboard origins)
CORS_ORIGIN=$GOVERNANCE_URL,$API_URL,$PROVIDER_URL,$COUNCIL_URL,$CLAIMER_URL
EOF

echo "  Generated: $GENERATED_DIR/env.api"
echo "Done."
