/**
 * Contract ABIs for Trustful Agents
 *
 * These are minimal ABIs containing only the functions/events needed by the SDK.
 * Full ABIs are generated by Foundry and available in contracts/out/
 */

export const CollateralVaultAbi = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initiateWithdrawal",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelWithdrawal",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeWithdrawal",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAccount",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "account",
        type: "tuple",
        components: [
          { name: "balance", type: "uint256" },
          { name: "lockedAmount", type: "uint256" },
          { name: "withdrawalInitiatedAt", type: "uint256" },
          { name: "withdrawalAmount", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAvailableBalance",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ name: "available", type: "uint256" }],
    stateMutability: "view",
  },
] as const;

export const TermsRegistryAbi = [
  {
    type: "function",
    name: "registerTerms",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "contentHash", type: "bytes32" },
      { name: "contentUri", type: "string" },
      { name: "maxPayoutPerClaim", type: "uint256" },
      { name: "councilId", type: "bytes32" },
    ],
    outputs: [{ name: "version", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getActiveTerms",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "terms",
        type: "tuple",
        components: [
          { name: "contentHash", type: "bytes32" },
          { name: "contentUri", type: "string" },
          { name: "maxPayoutPerClaim", type: "uint256" },
          { name: "councilId", type: "bytes32" },
          { name: "registeredAt", type: "uint256" },
          { name: "active", type: "bool" },
        ],
      },
      { name: "version", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMaxPayoutPerClaim",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ name: "maxPayout", type: "uint256" }],
    stateMutability: "view",
  },
] as const;

export const TrustfulValidatorAbi = [
  {
    type: "function",
    name: "isValidated",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ name: "isValid", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getValidationRecord",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "record",
        type: "tuple",
        components: [
          { name: "requestHash", type: "bytes32" },
          { name: "issuedAt", type: "uint256" },
          { name: "revokedAt", type: "uint256" },
          { name: "nonce", type: "uint256" },
          { name: "revocationReason", type: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "checkConditions",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "conditions",
        type: "tuple",
        components: [
          { name: "hasMinimumCollateral", type: "bool" },
          { name: "hasTermsRegistered", type: "bool" },
          { name: "hasValidMaxPayout", type: "bool" },
          { name: "isOwnerValid", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTrustInfo",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      { name: "collateralAmount", type: "uint256" },
      { name: "maxPayoutPerClaim", type: "uint256" },
      { name: "councilId", type: "bytes32" },
      { name: "isValid", type: "bool" },
    ],
    stateMutability: "view",
  },
] as const;

export const CouncilRegistryAbi = [
  {
    type: "function",
    name: "getCouncil",
    inputs: [{ name: "councilId", type: "bytes32" }],
    outputs: [
      {
        name: "council",
        type: "tuple",
        components: [
          { name: "councilId", type: "bytes32" },
          { name: "name", type: "string" },
          { name: "vertical", type: "string" },
          { name: "memberCount", type: "uint256" },
          { name: "quorumPercentage", type: "uint256" },
          { name: "claimDepositPercentage", type: "uint256" },
          { name: "votingPeriod", type: "uint256" },
          { name: "evidencePeriod", type: "uint256" },
          { name: "active", type: "bool" },
          { name: "createdAt", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isActiveMember",
    inputs: [
      { name: "councilId", type: "bytes32" },
      { name: "member", type: "address" },
    ],
    outputs: [{ name: "isMember", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateRequiredDeposit",
    inputs: [
      { name: "councilId", type: "bytes32" },
      { name: "claimAmount", type: "uint256" },
    ],
    outputs: [{ name: "deposit", type: "uint256" }],
    stateMutability: "view",
  },
] as const;

export const ClaimsManagerAbi = [
  {
    type: "function",
    name: "fileClaim",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "claimedAmount", type: "uint256" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "evidenceUri", type: "string" },
      { name: "paymentReceiptHash", type: "bytes32" },
    ],
    outputs: [{ name: "claimId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "castVote",
    inputs: [
      { name: "claimId", type: "uint256" },
      { name: "vote", type: "uint8" },
      { name: "approvedAmount", type: "uint256" },
      { name: "reasoning", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getClaim",
    inputs: [{ name: "claimId", type: "uint256" }],
    outputs: [
      {
        name: "claim",
        type: "tuple",
        components: [
          { name: "claimId", type: "uint256" },
          { name: "agentId", type: "uint256" },
          { name: "claimant", type: "address" },
          { name: "claimedAmount", type: "uint256" },
          { name: "approvedAmount", type: "uint256" },
          { name: "evidenceHash", type: "bytes32" },
          { name: "evidenceUri", type: "string" },
          { name: "paymentReceiptHash", type: "bytes32" },
          { name: "termsHashAtClaimTime", type: "bytes32" },
          { name: "termsVersionAtClaimTime", type: "uint256" },
          { name: "providerAtClaimTime", type: "address" },
          { name: "councilId", type: "bytes32" },
          { name: "claimantDeposit", type: "uint256" },
          { name: "lockedCollateral", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "filedAt", type: "uint256" },
          { name: "evidenceDeadline", type: "uint256" },
          { name: "votingDeadline", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimsByAgent",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [{ name: "claimIds", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimStats",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "stats",
        type: "tuple",
        components: [
          { name: "totalClaims", type: "uint256" },
          { name: "approvedClaims", type: "uint256" },
          { name: "rejectedClaims", type: "uint256" },
          { name: "pendingClaims", type: "uint256" },
          { name: "totalPaidOut", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "calculateRequiredDeposit",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "claimedAmount", type: "uint256" },
    ],
    outputs: [{ name: "deposit", type: "uint256" }],
    stateMutability: "view",
  },
] as const;

export const RulingExecutorAbi = [
  {
    type: "function",
    name: "executeRuling",
    inputs: [{ name: "claimId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canExecute",
    inputs: [{ name: "claimId", type: "uint256" }],
    outputs: [
      { name: "canExecute", type: "bool" },
      { name: "reason", type: "string" },
    ],
    stateMutability: "view",
  },
] as const;
